stages:
  - build
  - test
  - security
  - package
  - deploy

build:
  stage: build
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h
#stage ensures all unit and integration tests run automatically when i push code.
test:
  stage: test
  image: node:20
  services:
    - name: mysql:8
      alias: db
  ariables:
    DB_HOST: db
    DB_USER: root
    DB_PASSWORD: password123
    DB_NAME: contact_manager
  script:
    - npm install      # ensure dependencies are installed
    - npx mocha         # runs teh unit tests


include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

sast:
  stage: security

dependency_scanning:
  stage: security

package:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker run -d -p 3000:3000 --name contact-manager-app $CI_REGISTRY_IMAGE:latest