
services:
  db:
    image: mysql:8
    container_name: contact_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: contact_manager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: contact_manager_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: contact_manager
    depends_on:
      - db

volumes:
  db_data:
