name: Full CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password123
          MYSQL_DATABASE: contact_manager
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ppassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB_HOST: localhost  # Override for CI environment
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: contact_manager
      DB_PORT: 3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - name: Make Mocha executable
        run: chmod +x ./node_modules/.bin/mocha  
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h localhost -u root -ppassword123 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... Attempt $i"
            sleep 2
          done
      - name: Initialize database schema
        run: |
          mysql -h localhost -u root -ppassword123 contact_manager << EOF
          CREATE TABLE IF NOT EXISTS contacts (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255),
            phone VARCHAR(20),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
          
          INSERT INTO contacts (name, email, phone) VALUES
          ('John Doe', 'john@example.com', '123-456-7890'),
          ('Jane Smith', 'jane@example.com', '098-765-4321');
          EOF
      - name: Run tests
        run: npx --no-install mocha

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run security scans
        run: |
          echo "SAST scan simulated"
          npm audit --audit-level=high || true

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t contact-manager-app:latest .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (local simulation)
        run: echo "Deployment simulated - replace with cloud deploy commands"